### PR TITLE
Create new subproject

### PR DESCRIPTION
**Pull request by jszlenk**
Adding a method to create a new subproject
Arvados-DCO-1.1-Signed-off-by: Jakub Szlenk jakubszlenk@gmail.com

### CODE REVIEW

**Comment by kmajewski-bergregions** [comment]
@brettcs @tetron Can this be merged?

**Comment by tetron** [comment]
Yes it can, I apologize, this pull request was overlooked when we were merging other Java SDK PRs.

**Comment by MajewskiKrzysztof** [comment]
Thanks @tetron !
When do you plan next release?

**Comment by tetron** [comment]
@MajewskiKrzysztof this has been released in the 2.7.4 Arvados Java SDK https://arvados.org/release-notes/2.7.4/

**Pull request merged**
