### PR TITLE
Feature/compute driver openstack

### PR DESCRIPTION
**Pull request by lukaszimmermann**
This PR adds the OpenStack Compute Node driver for the Arvados Node Manager.

Some important remarks:
- the cloud names are assigned sequentially from compute-0 to compute-N; name is skipped if it is already 
  listed by `list_nodes()`. Hence, to avoid duplicate cloud names, a file lock is used which ensures that
  the code of `create_node()` is only processed once at a time, the filelock module must be installed in 
  Python.
- The node_secret is exported to the new node via cloud-init, which must therefore be installed on the
  used compute image. 
- The config must specify the location of the lockfile for creating new nodes.
- The config file must specify these IDs: `'image_id', 'flavor_id', 'network_id', 'security_group_id'`. Currently, only one item is allowed for each type.
- `sync_node` currently does not do anything useful. 
- the meta values associated with a compute node are set in the config.ini. Only nodes having all (!)
  meta values set to the chosen value will be listed in `list_nodes()`.

The logic of giving cloud names is different than in other drivers (does not use `compute-UUID`). I chose this method to avoid the need to rename the cloud node after it has been created. In `compute-N`, N is not the slot number (as one would want to have). This is due to the fact that the slot number has not been decided upon at the time the cloud node is created. It is selected once the first ping is received.

### CODE REVIEW

**Comment by tetron** [comment]
Thanks for you contribution!  We'll need some time to do a code review.  Would you be able to add some testing?  Also, does this depend on #61?

**Comment by lukaszimmermann** [comment]
Yes, I can add tests soon.
This PR does not depend on #61, though I did not test so far with  `assign_node_hostname: true`

**Comment by tfmorris** [comment]
From a process point of view, we need the commits signed off for substantial contributions like this.

Please review the requirements at https://dev.arvados.org/projects/arvados/wiki/Developer_Certificate_Of_Origin
and amend your commits to add Arvados-DCO-Signoff lines if you agree and meet all the requirements.

**Comment by tetron** [comment]
Another question, is this something you're using now, i.e. you already have a functioning Arvados cluster on OpenStack, or is this an ongoing development?

**Comment by lukaszimmermann** [comment]
I currently work on deploying Arvados on the de.NBI cloud. This is not a production system yet, but we have a CWL workflow that we want to offer soon. As de.NBI cloud uses OpenStack, I needed to write the compute node driver. I tested this the driver "a bit" and it seems to work fine. (Nodes are booted and shut down by the NodeManager as expected). The only problem that I see is that the `crunch_worker_state` is consistently `down` and that the nodes are all `unpaired`. I have not yet figured out why the pairing between Arvados nodes and compute nodes does not work yet.

**Comment by tetron** [comment]
@lukaszimmermann There are a few additional steps required for the compute node to self-register after it is booted by node manager.  They are covered in http://doc.arvados.org/install/crunch2-slurm/install-compute-node.html and http://doc.arvados.org/install/install-compute-ping.html

If you have more questions about configuring your compute node image, consider asking the mailing list:

http://lists.arvados.org/mailman/listinfo/arvados

**Comment by lukaszimmermann** [comment]
Thanks for the reference. I thoroughly read the install documentation and ended up using the same ping script that was described in the doc. The only difference is that I manage the dynamic DNS server externally (because I use `bind9` rather than `unbound`), so the ping script is extended with code that registers the newly created node at the DNS server.

I also saw that the `slurm_state` key never appears  in the node info section.  This results in the node reported as down. I still investigate why this is the case.

**Comment by lukaszimmermann** [comment]
I added the Arvados-DCO-Signoff lines

**Comment by tetron** [comment]
Closing old PRs

**Pull request closed without merging**
