### PR TITLE
enable universal wheels

### PR DESCRIPTION
**Pull request by graingert**
please can you release wheels with:

```
pipx run --spec=build python-build --sdist --wheel
pipx run twine upload dist/*
```

### CODE REVIEW

**Comment by mr-c** [comment]
I'm still not seeing wheels at https://pypi.org/project/arvados-cwl-runner/

**Comment by graingert** [comment]
@mr-c this PR will need merging before universal wheels will be distributed

**Comment by mr-c** [comment]
@graingert Agreed! I was also noting that even *non* universal wheels were not being uploaded to PyPI

**Comment by tetron** [comment]
I'm so sorry, this was overlooked and forgotten about.  We'll work on it and I've added an Arvados ticket to track it https://dev.arvados.org/issues/17013

**Comment by graingert** [comment]
Release instructions changed to use `build`

**Comment by tetron** [comment]
FYI the script that we actually use to publish packages are https://github.com/arvados/arvados/blob/master/build/run-build-packages-python-and-ruby.sh and https://github.com/arvados/arvados-dev/blob/master/jenkins/run_upload_packages.py and the infrastructure tweaking that actually needs to happen is teaching those scripts to create and upload wheels.

**Comment by cure** [comment]
An update - as of Arvados release 2.1.1, we now publish 'pure' wheels for Python 3 (e.g. https://pypi.org/project/arvados-python-client/#files). Since we have phase out Python 2, universal wheels are no longer needed, so I'm closing this PR. Thanks for your patience!

**Pull request closed without merging**
