### PR TITLE
Add \dontrun in documentation

### PR DESCRIPTION
**Pull request by AnetaSta22**
Needed to pass R CMD CHECK

### CODE REVIEW

**Comment by tetron** [comment]
Hi @AnetaSta22 thank you for this, I will see about merging it.

**Comment by AnetaSta22** [comment]
Hi @tetron great!. 
I am also working on a readme and more helpful documentation.

**Comment by AnetaSta22** [comment]
I will make a new PR.

**Comment by tetron** [comment]
Merge ticket here https://dev.arvados.org/issues/20660

**Comment by tetron** [comment]
Merged at 9d876a230cd108d61b7748d84a165bb627ac665f (required a rebase and a little tweaking which is why it isn't a straight merge).

**Pull request closed without merging**
